server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        port: 8090
spring:
    profiles:
        active: rabbitmq
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
      name: druidDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
          driver-class-name: com.mysql.cj.jdbc.Driver
          datasourcename: woxuv12
          url: jdbc:mysql://127.0.0.1/${spring.datasource.druid.datasourcename}?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: root
          password: 123456
          filters: stat,wall,config
          max-active: 1000
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 50
          max-pool-prepared-statement-per-connection-size: 20
    ## Redis 配置
    redis:
        ## Redis数据库索引（默认为0）
        database: 0
        ## Redis服务器地址
        host: 127.0.0.1
        ## Redis服务器连接端口
        port: 6379
        ## Redis服务器连接密码（默认为空）
        password: 123456
        jedis:
            pool:
                ## 连接池最大连接数（使用负值表示没有限制）
                max-active: -1
                ## 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                ## 连接池中的最大空闲连接
                max-idle: 1000
                ## 连接池中的最小空闲连接
                min-idle: 0
        ## 连接超时时间（毫秒）
        timeout: 1200